## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
create_clock -period 10.000 -name clk_pin -waveform {0.000 5.000} -add [get_ports clk_in]

## Switches
set_property PACKAGE_PIN V17 [get_ports {s_switches_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[0]}]
set_property PACKAGE_PIN V16 [get_ports {s_switches_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[1]}]
set_property PACKAGE_PIN W16 [get_ports {s_switches_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[2]}]
set_property PACKAGE_PIN W17 [get_ports {s_switches_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[3]}]
set_property PACKAGE_PIN W15 [get_ports {s_switches_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[4]}]
set_property PACKAGE_PIN V15 [get_ports {s_switches_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[5]}]
set_property PACKAGE_PIN W14 [get_ports {s_switches_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[6]}]
set_property PACKAGE_PIN W13 [get_ports {s_switches_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[7]}]
set_property PACKAGE_PIN V2 [get_ports {s_switches_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[8]}]
set_property PACKAGE_PIN T3 [get_ports {s_switches_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[9]}]
set_property PACKAGE_PIN T2 [get_ports {s_switches_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[10]}]
set_property PACKAGE_PIN R3 [get_ports {s_switches_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[11]}]
set_property PACKAGE_PIN W2 [get_ports {s_switches_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[12]}]
set_property PACKAGE_PIN U1 [get_ports {s_switches_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[13]}]
set_property PACKAGE_PIN T1 [get_ports {s_switches_in[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[14]}]
set_property PACKAGE_PIN R2 [get_ports {s_switches_in[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s_switches_in[15]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {led_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]
set_property PACKAGE_PIN E19 [get_ports {led_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property PACKAGE_PIN U19 [get_ports {led_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]
set_property PACKAGE_PIN V19 [get_ports {led_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]
set_property PACKAGE_PIN W18 [get_ports {led_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[4]}]
set_property PACKAGE_PIN U15 [get_ports {led_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[5]}]
set_property PACKAGE_PIN U14 [get_ports {led_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[6]}]
set_property PACKAGE_PIN V14 [get_ports {led_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[7]}]
set_property PACKAGE_PIN V13 [get_ports {led_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[8]}]
set_property PACKAGE_PIN V3 [get_ports {led_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[9]}]
set_property PACKAGE_PIN W3 [get_ports {led_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[10]}]
set_property PACKAGE_PIN U3 [get_ports {led_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[11]}]
set_property PACKAGE_PIN P3 [get_ports {led_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[12]}]
set_property PACKAGE_PIN N3 [get_ports {led_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[13]}]
set_property PACKAGE_PIN P1 [get_ports {led_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[14]}]
set_property PACKAGE_PIN L1 [get_ports {led_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[15]}]

##7 segment display
set_property PACKAGE_PIN W7 [get_ports {seg7_hex_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_hex_out[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg7_hex_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_hex_out[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg7_hex_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_hex_out[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg7_hex_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_hex_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg7_hex_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_hex_out[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg7_hex_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_hex_out[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg7_hex_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_hex_out[6]}]
set_property PACKAGE_PIN V7 [get_ports {seg7_hex_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_hex_out[7]}]
set_property PACKAGE_PIN U2 [get_ports {seg7_sel_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_sel_out[0]}]
set_property PACKAGE_PIN U4 [get_ports {seg7_sel_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_sel_out[1]}]
set_property PACKAGE_PIN V4 [get_ports {seg7_sel_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_sel_out[2]}]
set_property PACKAGE_PIN W4 [get_ports {seg7_sel_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7_sel_out[3]}]

##Buttons
set_property PACKAGE_PIN U18 [get_ports reset_in]
set_property IOSTANDARD LVCMOS33 [get_ports reset_in]
set_property PACKAGE_PIN T18 [get_ports p_btn_U_in]
set_property IOSTANDARD LVCMOS33 [get_ports p_btn_U_in]
set_property PACKAGE_PIN W19 [get_ports p_btn_L_in]
set_property IOSTANDARD LVCMOS33 [get_ports p_btn_L_in]
set_property PACKAGE_PIN T17 [get_ports p_btn_R_in]
set_property IOSTANDARD LVCMOS33 [get_ports p_btn_R_in]
set_property PACKAGE_PIN U17 [get_ports p_btn_D_in]
set_property IOSTANDARD LVCMOS33 [get_ports p_btn_D_in]

##USB-RS232 Interface
set_property PACKAGE_PIN B18 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property PACKAGE_PIN A18 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]