# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sources_1/constraints.xdc

# Block Designs: bd/mb_system/mb_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system || ORIG_REF_NAME==mb_system}]

# IP: bd/mb_system/ip/mb_system_microblaze_0_0/mb_system_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_microblaze_0_0 || ORIG_REF_NAME==mb_system_microblaze_0_0}]

# IP: bd/mb_system/ip/mb_system_dlmb_v10_0/mb_system_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_dlmb_v10_0 || ORIG_REF_NAME==mb_system_dlmb_v10_0}]

# IP: bd/mb_system/ip/mb_system_ilmb_v10_0/mb_system_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_ilmb_v10_0 || ORIG_REF_NAME==mb_system_ilmb_v10_0}]

# IP: bd/mb_system/ip/mb_system_dlmb_bram_if_cntlr_0/mb_system_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_system_dlmb_bram_if_cntlr_0}]

# IP: bd/mb_system/ip/mb_system_ilmb_bram_if_cntlr_0/mb_system_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_system_ilmb_bram_if_cntlr_0}]

# IP: bd/mb_system/ip/mb_system_lmb_bram_0/mb_system_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_lmb_bram_0 || ORIG_REF_NAME==mb_system_lmb_bram_0}]

# IP: bd/mb_system/ip/mb_system_rst_clk_wiz_1_100M_0/mb_system_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_system_rst_clk_wiz_1_100M_0}]

# IP: bd/mb_system/ip/mb_system_axi_gpio_0_0/mb_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_axi_gpio_0_0 || ORIG_REF_NAME==mb_system_axi_gpio_0_0}]

# IP: bd/mb_system/ip/mb_system_microblaze_0_axi_periph_0/mb_system_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_system_microblaze_0_axi_periph_0}]

# IP: bd/mb_system/ip/mb_system_gpio_leds_0/mb_system_gpio_leds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_gpio_leds_0 || ORIG_REF_NAME==mb_system_gpio_leds_0}]

# IP: bd/mb_system/ip/mb_system_gpio_s_switches_0/mb_system_gpio_s_switches_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_gpio_s_switches_0 || ORIG_REF_NAME==mb_system_gpio_s_switches_0}]

# IP: bd/mb_system/ip/mb_system_gpio_leds_1/mb_system_gpio_leds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_gpio_leds_1 || ORIG_REF_NAME==mb_system_gpio_leds_1}]

# IP: bd/mb_system/ip/mb_system_gpio_7seg_0/mb_system_gpio_7seg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_gpio_7seg_0 || ORIG_REF_NAME==mb_system_gpio_7seg_0}]

# IP: bd/mb_system/ip/mb_system_gpio_s_switches_1/mb_system_gpio_s_switches_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_gpio_s_switches_1 || ORIG_REF_NAME==mb_system_gpio_s_switches_1}]

# IP: bd/mb_system/ip/mb_system_gpio_s_switches_2/mb_system_gpio_s_switches_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_gpio_s_switches_2 || ORIG_REF_NAME==mb_system_gpio_s_switches_2}]

# IP: bd/mb_system/ip/mb_system_gpio_s_switches_3/mb_system_gpio_s_switches_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_gpio_s_switches_3 || ORIG_REF_NAME==mb_system_gpio_s_switches_3}]

# IP: bd/mb_system/ip/mb_system_gpio_vga_hs_0/mb_system_gpio_vga_hs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_gpio_vga_hs_0 || ORIG_REF_NAME==mb_system_gpio_vga_hs_0}]

# IP: bd/mb_system/ip/mb_system_gpio_p_btn_u_0/mb_system_gpio_p_btn_u_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_gpio_p_btn_u_0 || ORIG_REF_NAME==mb_system_gpio_p_btn_u_0}]

# IP: bd/mb_system/ip/mb_system_gpio_p_btn_u_1/mb_system_gpio_p_btn_u_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_gpio_p_btn_u_1 || ORIG_REF_NAME==mb_system_gpio_p_btn_u_1}]

# IP: bd/mb_system/ip/mb_system_gpio_p_btn_u_2/mb_system_gpio_p_btn_u_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_gpio_p_btn_u_2 || ORIG_REF_NAME==mb_system_gpio_p_btn_u_2}]

# IP: bd/mb_system/ip/mb_system_axi_uartlite_0_0/mb_system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_axi_uartlite_0_0 || ORIG_REF_NAME==mb_system_axi_uartlite_0_0}]

# IP: bd/mb_system/ip/mb_system_mdm_0_0/mb_system_mdm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_mdm_0_0 || ORIG_REF_NAME==mb_system_mdm_0_0}]

# IP: bd/mb_system/ip/mb_system_fit_timer_0_0/mb_system_fit_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_fit_timer_0_0 || ORIG_REF_NAME==mb_system_fit_timer_0_0}]

# IP: bd/mb_system/ip/mb_system_axi_intc_0_0/mb_system_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_axi_intc_0_0 || ORIG_REF_NAME==mb_system_axi_intc_0_0}]

# IP: bd/mb_system/ip/mb_system_xlconcat_0_0/mb_system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_xlconcat_0_0 || ORIG_REF_NAME==mb_system_xlconcat_0_0}]

# IP: bd/mb_system/ip/mb_system_xbar_0/mb_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_xbar_0 || ORIG_REF_NAME==mb_system_xbar_0}]

# XDC: bd/mb_system/ip/mb_system_microblaze_0_0/mb_system_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_microblaze_0_0 || ORIG_REF_NAME==mb_system_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_microblaze_0_0/mb_system_microblaze_0_0_ooc_debug.xdc

# XDC: bd/mb_system/ip/mb_system_microblaze_0_0/mb_system_microblaze_0_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_dlmb_v10_0/mb_system_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_dlmb_v10_0 || ORIG_REF_NAME==mb_system_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_dlmb_v10_0/mb_system_dlmb_v10_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_ilmb_v10_0/mb_system_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_ilmb_v10_0 || ORIG_REF_NAME==mb_system_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_ilmb_v10_0/mb_system_ilmb_v10_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_dlmb_bram_if_cntlr_0/mb_system_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_ilmb_bram_if_cntlr_0/mb_system_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_lmb_bram_0/mb_system_lmb_bram_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_rst_clk_wiz_1_100M_0/mb_system_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_system_rst_clk_wiz_1_100M_0}]

# XDC: bd/mb_system/ip/mb_system_rst_clk_wiz_1_100M_0/mb_system_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mb_system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_system_rst_clk_wiz_1_100M_0}]

# XDC: bd/mb_system/ip/mb_system_rst_clk_wiz_1_100M_0/mb_system_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_axi_gpio_0_0/mb_system_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_axi_gpio_0_0 || ORIG_REF_NAME==mb_system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_axi_gpio_0_0/mb_system_axi_gpio_0_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_axi_gpio_0_0/mb_system_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_axi_gpio_0_0 || ORIG_REF_NAME==mb_system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_leds_0/mb_system_gpio_leds_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_leds_0 || ORIG_REF_NAME==mb_system_gpio_leds_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_leds_0/mb_system_gpio_leds_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_gpio_leds_0/mb_system_gpio_leds_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_leds_0 || ORIG_REF_NAME==mb_system_gpio_leds_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_s_switches_0/mb_system_gpio_s_switches_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_s_switches_0 || ORIG_REF_NAME==mb_system_gpio_s_switches_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_s_switches_0/mb_system_gpio_s_switches_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_gpio_s_switches_0/mb_system_gpio_s_switches_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_s_switches_0 || ORIG_REF_NAME==mb_system_gpio_s_switches_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_leds_1/mb_system_gpio_leds_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_leds_1 || ORIG_REF_NAME==mb_system_gpio_leds_1}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_leds_1/mb_system_gpio_leds_1_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_gpio_leds_1/mb_system_gpio_leds_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_leds_1 || ORIG_REF_NAME==mb_system_gpio_leds_1}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_7seg_0/mb_system_gpio_7seg_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_7seg_0 || ORIG_REF_NAME==mb_system_gpio_7seg_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_7seg_0/mb_system_gpio_7seg_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_gpio_7seg_0/mb_system_gpio_7seg_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_7seg_0 || ORIG_REF_NAME==mb_system_gpio_7seg_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_s_switches_1/mb_system_gpio_s_switches_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_s_switches_1 || ORIG_REF_NAME==mb_system_gpio_s_switches_1}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_s_switches_1/mb_system_gpio_s_switches_1_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_gpio_s_switches_1/mb_system_gpio_s_switches_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_s_switches_1 || ORIG_REF_NAME==mb_system_gpio_s_switches_1}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_s_switches_2/mb_system_gpio_s_switches_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_s_switches_2 || ORIG_REF_NAME==mb_system_gpio_s_switches_2}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_s_switches_2/mb_system_gpio_s_switches_2_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_gpio_s_switches_2/mb_system_gpio_s_switches_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_s_switches_2 || ORIG_REF_NAME==mb_system_gpio_s_switches_2}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_s_switches_3/mb_system_gpio_s_switches_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_s_switches_3 || ORIG_REF_NAME==mb_system_gpio_s_switches_3}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_s_switches_3/mb_system_gpio_s_switches_3_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_gpio_s_switches_3/mb_system_gpio_s_switches_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_s_switches_3 || ORIG_REF_NAME==mb_system_gpio_s_switches_3}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_vga_hs_0/mb_system_gpio_vga_hs_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_vga_hs_0 || ORIG_REF_NAME==mb_system_gpio_vga_hs_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_vga_hs_0/mb_system_gpio_vga_hs_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_gpio_vga_hs_0/mb_system_gpio_vga_hs_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_vga_hs_0 || ORIG_REF_NAME==mb_system_gpio_vga_hs_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_p_btn_u_0/mb_system_gpio_p_btn_u_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_p_btn_u_0 || ORIG_REF_NAME==mb_system_gpio_p_btn_u_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_p_btn_u_0/mb_system_gpio_p_btn_u_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_gpio_p_btn_u_0/mb_system_gpio_p_btn_u_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_p_btn_u_0 || ORIG_REF_NAME==mb_system_gpio_p_btn_u_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_p_btn_u_1/mb_system_gpio_p_btn_u_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_p_btn_u_1 || ORIG_REF_NAME==mb_system_gpio_p_btn_u_1}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_p_btn_u_1/mb_system_gpio_p_btn_u_1_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_gpio_p_btn_u_1/mb_system_gpio_p_btn_u_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_p_btn_u_1 || ORIG_REF_NAME==mb_system_gpio_p_btn_u_1}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_p_btn_u_2/mb_system_gpio_p_btn_u_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_p_btn_u_2 || ORIG_REF_NAME==mb_system_gpio_p_btn_u_2}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_gpio_p_btn_u_2/mb_system_gpio_p_btn_u_2_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_gpio_p_btn_u_2/mb_system_gpio_p_btn_u_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_gpio_p_btn_u_2 || ORIG_REF_NAME==mb_system_gpio_p_btn_u_2}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_axi_uartlite_0_0/mb_system_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_axi_uartlite_0_0 || ORIG_REF_NAME==mb_system_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_axi_uartlite_0_0/mb_system_axi_uartlite_0_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_axi_uartlite_0_0/mb_system_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_axi_uartlite_0_0 || ORIG_REF_NAME==mb_system_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_mdm_0_0/mb_system_mdm_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_mdm_0_0 || ORIG_REF_NAME==mb_system_mdm_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_mdm_0_0/mb_system_mdm_0_0_ooc_trace.xdc

# XDC: bd/mb_system/ip/mb_system_fit_timer_0_0/mb_system_fit_timer_0_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_axi_intc_0_0/mb_system_axi_intc_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_axi_intc_0_0 || ORIG_REF_NAME==mb_system_axi_intc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_axi_intc_0_0/mb_system_axi_intc_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_axi_intc_0_0 || ORIG_REF_NAME==mb_system_axi_intc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mb_system/ip/mb_system_axi_intc_0_0/mb_system_axi_intc_0_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_xbar_0/mb_system_xbar_0_ooc.xdc

# XDC: bd/mb_system/mb_system_ooc.xdc
