
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
* 
* Use of the Software is limited solely to applications:
*(a) running on a Xilinx device, or
*(b) that interact with a Xilinx device through a bus or interconnect.
*
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
*XILINX CONSORTIUM BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
*Except as contained in this notice, the name of the Xilinx shall not be used
*in advertising or otherwise to promote the sale, use or other dealings in
*this Software without prior written authorization from Xilinx.
*

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_GPIO_7SEG_HEX_OUT_DEVICE_ID,
		XPAR_GPIO_7SEG_HEX_OUT_BASEADDR,
		XPAR_GPIO_7SEG_HEX_OUT_INTERRUPT_PRESENT,
		XPAR_GPIO_7SEG_HEX_OUT_IS_DUAL
	},
	{
		XPAR_GPIO_7SEG_SEL_DEVICE_ID,
		XPAR_GPIO_7SEG_SEL_BASEADDR,
		XPAR_GPIO_7SEG_SEL_INTERRUPT_PRESENT,
		XPAR_GPIO_7SEG_SEL_IS_DUAL
	},
	{
		XPAR_GPIO_LEDS_DEVICE_ID,
		XPAR_GPIO_LEDS_BASEADDR,
		XPAR_GPIO_LEDS_INTERRUPT_PRESENT,
		XPAR_GPIO_LEDS_IS_DUAL
	},
	{
		XPAR_GPIO_P_BTN_D_DEVICE_ID,
		XPAR_GPIO_P_BTN_D_BASEADDR,
		XPAR_GPIO_P_BTN_D_INTERRUPT_PRESENT,
		XPAR_GPIO_P_BTN_D_IS_DUAL
	},
	{
		XPAR_GPIO_P_BTN_L_DEVICE_ID,
		XPAR_GPIO_P_BTN_L_BASEADDR,
		XPAR_GPIO_P_BTN_L_INTERRUPT_PRESENT,
		XPAR_GPIO_P_BTN_L_IS_DUAL
	},
	{
		XPAR_GPIO_P_BTN_R_DEVICE_ID,
		XPAR_GPIO_P_BTN_R_BASEADDR,
		XPAR_GPIO_P_BTN_R_INTERRUPT_PRESENT,
		XPAR_GPIO_P_BTN_R_IS_DUAL
	},
	{
		XPAR_GPIO_P_BTN_U_DEVICE_ID,
		XPAR_GPIO_P_BTN_U_BASEADDR,
		XPAR_GPIO_P_BTN_U_INTERRUPT_PRESENT,
		XPAR_GPIO_P_BTN_U_IS_DUAL
	},
	{
		XPAR_GPIO_S_SWITCHES_DEVICE_ID,
		XPAR_GPIO_S_SWITCHES_BASEADDR,
		XPAR_GPIO_S_SWITCHES_INTERRUPT_PRESENT,
		XPAR_GPIO_S_SWITCHES_IS_DUAL
	},
	{
		XPAR_GPIO_VGA_COLOUR_OUT_DEVICE_ID,
		XPAR_GPIO_VGA_COLOUR_OUT_BASEADDR,
		XPAR_GPIO_VGA_COLOUR_OUT_INTERRUPT_PRESENT,
		XPAR_GPIO_VGA_COLOUR_OUT_IS_DUAL
	},
	{
		XPAR_GPIO_VGA_HS_DEVICE_ID,
		XPAR_GPIO_VGA_HS_BASEADDR,
		XPAR_GPIO_VGA_HS_INTERRUPT_PRESENT,
		XPAR_GPIO_VGA_HS_IS_DUAL
	},
	{
		XPAR_GPIO_VGA_REGION_DEVICE_ID,
		XPAR_GPIO_VGA_REGION_BASEADDR,
		XPAR_GPIO_VGA_REGION_INTERRUPT_PRESENT,
		XPAR_GPIO_VGA_REGION_IS_DUAL
	},
	{
		XPAR_GPIO_VGS_VS_DEVICE_ID,
		XPAR_GPIO_VGS_VS_BASEADDR,
		XPAR_GPIO_VGS_VS_INTERRUPT_PRESENT,
		XPAR_GPIO_VGS_VS_IS_DUAL
	}
};


