webtalk_init -webtalk_dir F:\\Amir_Hamzah\\University_of_Edinburgh\\Studies\\2nd_year\\Engineering_Software_3\\Assessment_1_Calculator\\Calculator_codes\\es3_hw_assmnt_1\\es3_hw_assmnt_1.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 25 00:26:21 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3tdj9c1pubc6madq0kjvi7tukg" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_22" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1606245035887" -context "sdk\\\\bsp/1606245035887"
webtalk_add_data -client sdk -key hwid -value "1604149646489" -context "sdk\\\\bsp/1606245035887"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1606245035887"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1606245035887"
webtalk_add_data -client sdk -key uid -value "1606245040236" -context "sdk\\\\application/1606245040236"
webtalk_add_data -client sdk -key hwid -value "1604149646489" -context "sdk\\\\application/1606245040236"
webtalk_add_data -client sdk -key bspid -value "1606245035887" -context "sdk\\\\application/1606245040236"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1606245040236"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1606245040236"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1606245040236"
webtalk_transmit -clientid 789087348 -regid "" -xml F:\\Amir_Hamzah\\University_of_Edinburgh\\Studies\\2nd_year\\Engineering_Software_3\\Assessment_1_Calculator\\Calculator_codes\\es3_hw_assmnt_1\\es3_hw_assmnt_1.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\Amir_Hamzah\\University_of_Edinburgh\\Studies\\2nd_year\\Engineering_Software_3\\Assessment_1_Calculator\\Calculator_codes\\es3_hw_assmnt_1\\es3_hw_assmnt_1.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\Amir_Hamzah\\University_of_Edinburgh\\Studies\\2nd_year\\Engineering_Software_3\\Assessment_1_Calculator\\Calculator_codes\\es3_hw_assmnt_1\\es3_hw_assmnt_1.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
